---
language: python

python:
- "3.5"
- "3.6"

install:
- pip install -r testing-requirements.txt
- pip install .

script:
- tests/run_tests.sh

deploy:
- provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never